### ISSUE TITLE
new webtest broke our tests

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.testbrowser#30]
See https://github.com/zopefoundation/zope.testbrowser/pull/29#issuecomment-297627544

**Comment by icemac** [comment]
Pinning our dependencies to `webtest < 2.0.27` in 8e3c130 to get our tests green again.

**Comment by fschulze** [comment]
Also see https://github.com/Pylons/webtest/pull/185

**Comment by icemac** [comment]
@fschulze Thank you for getting this fixed in webtest. I am going to update `zope.testbrowser` to use the new version.
