### ISSUE TITLE
Bug since switch from mechanize

### ISSUE THREAD

**Issue by fschulze** [zopefoundation/zope.testbrowser#31]
The behaviour related to setting radio controls has changed in some cases.

I added a test case in https://github.com/zopefoundation/zope.testbrowser/compare/master...fschulze:radio-master.

I added the same one for 4.0.4 in https://github.com/zopefoundation/zope.testbrowser/compare/4.0.4...fschulze:radio-4.0.4 to show that it works correctly with mechanize.

**Comment by fschulze** [comment]
The tests in https://github.com/fschulze/zope.testbrowser/tree/radio-4.0.4 work when using the buildout and running the ``test`` script.

**Comment by mgedmin** [comment]
The failure looks like this:
```
**********************************************************************
File "narrative.rst", line ?, in default
Failed example:
    browser.getControl(name='radio-value-a').getControl(value='true', index=0)
Expected:
    <ItemControl name='radio-value-a' type='radio' optionValue='true' selected=False>
Got:
    <ItemControl name='radio-value-a' type='radio' optionValue='true' selected=True>
**********************************************************************
```

**Comment by mgedmin** [comment]
The problem here is that `RadioItemControl.selected = True` is translated into `RadioListControl.value = RadioItemControl.value`, which cannot disambiguate items with the same value.

We could be assigning to WebTest's `Radio` control's `selectedIndex` instead of `value` to avoid this issue.
