### ISSUE TITLE
displayValue setter silently ignores values which are not in displayOptions

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.testbrowser#44]
Given I have a form:

```html
<form>
  <select name="a">
    <option value="b" selected="selected">b</option>
 </select>
</form>
```

Trying to select something which is not an option using:

```python
browser.getControl(name="a").displayValue = ['c']
```

silently ignores the unknown values. This results in no selected options in the example above.

I think in version 4.x an error was raised because there is no `displayOption` with the required title. (But I currently do not have code at hand to check this as 4.x calls into `mechanize` to select the value.)
The current behaviour is error prone for typos.

I propose to raise an exception (like `KeyError`) in this case.

Any suggestions?

**Comment by mgedmin** [comment]
This is also a backwards-compatibility issue.  I've a functional test I'm trying to migrate from mechanize-based zope.testbrowser that expects invalid choices to raise an ItemNotFoundError:

```rst
    >>> browser.getControl(name='form.goal_choice').displayValue = ['Client']
    Traceback (most recent call last):
    ...
    ItemNotFoundError: Client
```
