### ISSUE TITLE
Tests are broken on master

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.testbrowser#62]
See https://travis-ci.org/zopefoundation/zope.testbrowser/builds/485980587

**Comment by mgedmin** [comment]
I've looked at it, and ugh.  Dealing with long narrative doctests where the only test runner is `tox -e docs` is like walking through mud.

Something changed in webob's cookie parser?  Or we're not using it correctly?  I noticed two problems:
- using a space in a cookie's comment field causes a RuntimeWarning from webob (but the space gets encoded as %20, correctly, like the doctest expects)
- cookie expiration date gets lost somewhere

The last successful build was https://travis-ci.org/zopefoundation/zope.testbrowser/builds/472125193. The first failed build was https://travis-ci.org/zopefoundation/zope.testbrowser/builds/474117777.
The difference (looking at the Python 2.7 job):
- successful build had beautifulsoup4 4.6.3
- failed build had beautifulsoup4 4.7.0 (and also got a new dependency, backports.functools-lru-cache-1.5, but I don't think it is relevant)

Both builds had the same zope.testbrowser commit and had the same webob version.

**Comment by mgedmin** [comment]
> cookie expiration date gets lost somewhere (on my machine)

This is because the tests are sensitive to the user's locale!  :globe_with_meridians: 

If I set `LC_TIME=C`, I can reproduce the KeyError problem I see on Travis.

(This might be an actual bug lurking somewhere!)

**Comment by mgedmin** [comment]
THE BLOODY NARRATIVE TEST SETS A COOKIE WITH AN EXPIRATION DATE OF JANUARY THE FIRST TWO THOUSAND AND NINETEEN ANNO DOMINI.

Nice :timer_clock: :bomb: !
