### ISSUE TITLE
Allow option to prevent auto redirection  

### ISSUE THREAD

**Issue by nazrulworld** [zopefoundation/zope.testbrowser#79]
I saw there always following Location URL, 
https://github.com/zopefoundation/zope.testbrowser/blob/master/src/zope/testbrowser/browser.py#L278

but previously in an older version, I used to `browser.mech_browser.set_handle_redirect(False)`

Is there any way to do something like this?

**Comment by mgedmin** [comment]
I'd be happy to review a PR implementing something like this.  (Maybe a `browser.followRedirects = True/False`?  Like we currently have a `browser.handleErrors` switch.)
