### ISSUE TITLE
Browser._preparedRequest is a bit overenthusiastic about setting Referer

### ISSUE THREAD

**Issue by cjwatson** [zopefoundation/zope.testbrowser#87]
`mechanize` used to have this comment in its Referer header handling:

```
        # See RFC 2616 14.36.  The only times we know the source of the
        # request URI has a URI associated with it are redirect, and
        # Browser.click() / Browser.submit() / Browser.follow_link().
        # Otherwise, it's the user's job to add any Referer header before
        # .open()ing.
```

By contrast, if `self.url` is set at the start of `Browser._preparedRequest`, it just sets Referer to that.  This means that if you do `browser.open()` twice in a row, the second one gets its Referer set to the first URL.

`mechanize`'s behaviour was clearly more correct here.  The RFC it quotes says: "The Referer field MUST NOT be sent if the Request-URI was obtained from a source that does not have its own URI, such as input from the user keyboard."  In the context of a test browser, `browser.open` is analogous to input from the user keyboard and should not result in sending a Referer header.

I ran into some very confusing test failures in Launchpad that I eventually tracked down to this.  I hacked around it by doing `browser._response = None` just before the relevant `browser.open()` calls.

**Comment by mgedmin** [comment]
Sounds like a bug to me!  +1 for fixing it.
