### ISSUE TITLE
Prominently document backwards-incompatible changes in zope.testbrowser 5.0.0

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.testbrowser#9]
The changelog for version 5.0.0 should clearly document which zope.testbrowser APIs have disappeared, and what users are supposed to do when they upgrade their zope.testbrowser.

**Comment by mgedmin** [comment]
Commits that fix this (from 2013):
- 2741cb0d3499f1ce2bd7a1eba5dc9e73a8074d8e
- 27570eded8c98136e917b564c8ad678f415277ce

I still haven't found the time to test it (I planned to do it by [converting zodbbrowser](https://github.com/mgedmin/zodbbrowser/issues/20)).

**Comment by florianpilz** [comment]
@mgedmin Hi Marius! We are just trying to migrate some other zope packages to use the new testbrowser. Alas, I think that your migration docu is wrong. The prose in the beginning is concisely written and correct, but the code example does not use `zope.testbrowser.wsgi.Layer` at all.

For reference, here is the code snippet from the CHANGES.rst:

        # my/package/tests/test_all.py
        import doctest
        from zope.app.wsgi.testlayer import BrowserLayer
        import my.package.tests

        MyFtestLayer = BrowserLayer(my.package.tests, 'ftesting.zcml')

        def test_suite():
            suite = doctest.DocFileSuite('test.txt', ...)
            suite.layer = MyFtestLayer
            return suite

Yes, `zope.app.wsgi.testlayer.BrowserLayer` implements a `make_wsgi_app`, but without combining it with `zope.testbrowser.wsgi.Layer` the global `zope.testbrowser.wsgi._APP_UNDER_TEST` will not be set. Is it a typo or what was your rational behind this code snippet?

**Comment by florianpilz** [comment]
@mgedmin Since I saw no possibility to combine `zope.app.wsgi.testlayer.BrowserLayer` and `zope.testbrowser.wsgi.Layer` I created another layer (have a look at #18).

**Comment by mgedmin** [comment]
I'm not surprised at all if the docs are wrong.  Unfortunately, I last touched zope.testbrowser sufficiently long ago that I don't remember anything about anything.  Welp!

There must be some ported zope.* packages that use the zope.testbrowser alpha releases to support Python 3, aren't there?  You could take a look at how they do things.

**Comment by florianpilz** [comment]
@mgedmin Thanks for the feedback. I looked up the packages using `zope.testbrowser` that you listed in #11, but none of these are already ported to Python 3. 😱 Therefore I will adjust the migration docu in #18.

**Comment by florianpilz** [comment]
I think we can close this issue. If the documentation is still incorrect we will fix it as we go.
